version: '3.8'

services:
  wordpress:
    build: 
      context: .
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      - db
      - redis
    volumes:
      - ${WP_CONTENT_DIR}:/var/www/html/wp-content
      - ${UPLOADS_INI}:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', '${REDIS_HOST}');
        define('WP_CACHE', true);
        define('WP_ENVIRONMENT_TYPE', '${ENVIRONMENT}');
        define('FS_METHOD', 'direct');
    command: >
      sh -c '
        install-plugins.sh &
        php-fpm
      '

  webserver:
    image: nginx:latest
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
      - ${NGINX_CONF}:/etc/nginx/nginx.conf:ro
      - ${WP_CONTENT_DIR}:/var/www/html/wp-content
      - ./modsecurity.conf:/etc/nginx/modsecurity.conf:ro
      - ./owasp-modsecurity-crs:/etc/nginx/modsecurity/owasp-modsecurity-crs:ro
    depends_on:
      - wordpress

  db:
    image: mysql:8.0
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: redis:latest
    volumes:
      - ${REDIS_DATA_DIR}:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${WORDPRESS_DB_HOST}
      PMA_PORT: 3306
    ports:
      - "${PHPMYADMIN_PORT}:80"

volumes:
  db_data:
  redis_data: